
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 27 22:28:03 CST 2018
//----------------------------------------------------

package compiflex;

/** CUP generated class containing symbol constants. */
public class MySymbol {
  /* terminals */
  public static final int MENOS = 16;
  public static final int PARAMLIST = 10;
  public static final int PUNTOYCOMA = 13;
  public static final int PLUS = 15;
  public static final int INT = 19;
  public static final int IGUAL = 14;
  public static final int DIGIT = 4;
  public static final int RETURN = 12;
  public static final int PARENC = 11;
  public static final int PARENA = 9;
  public static final int LLAVEC = 7;
  public static final int POR = 17;
  public static final int LLAVEA = 6;
  public static final int ID = 3;
  public static final int PUBLIC = 5;
  public static final int STRING = 2;
  public static final int FLOAT = 20;
  public static final int EOF = 0;
  public static final int DOBLE = 21;
  public static final int DIV = 18;
  public static final int error = 1;
  public static final int VOID = 8;
}

